import test from "node:test";
import assert from "node:assert/strict";
import canonicalExample from "../examples/nexus-atlas-canonical-admission-v0.1.json" with { type: "json" };
import { buildCanonicalAdmissionPlanV01, applyCanonicalAdmissionPlanV01 } from "../experience/context-v02/canonical-admission.mjs";
import { CanonicalAdmissionError, deepEqual } from "../experience/context-v02/canonical-admission-validator.mjs";
import { acceptedGraph, acceptedAdmissionExample, planFor, planWithCapture, authorizedIds, candidateOf } from "./helpers/canonical-admission-fixtures.mjs";

const POLICY = canonicalExample.input.policyVersion;
function expectCode(fn, code) { assert.throws(fn, error => error instanceof CanonicalAdmissionError && error.code === code); }
function build(graph, plan, ids) { return buildCanonicalAdmissionPlanV01({ graph, plan, policyVersion: POLICY, authorizedCandidateIds: ids }); }
function apply(graph, plan, admission, ids) { return applyCanonicalAdmissionPlanV01({ graph, importPlan: plan, admissionPlan: admission, authorizedCandidateIds: ids }); }
const allPlan = () => planFor(["repository", "branch", "commit", "issue", "pull_request", "release", "tag"]);
const allIds = plan => authorizedIds(plan);

test("accepted example build is deepEqual", () => { const plan = allPlan(); assert.deepEqual(build(acceptedGraph(), plan, allIds(plan)), acceptedAdmissionExample().admissionPlan); });
test("accepted example apply appends eight Evidence nodes", () => { const plan = allPlan(); const graph = acceptedGraph(); const before = structuredClone(graph); const result = apply(graph, plan, build(graph, plan, allIds(plan)), allIds(plan)); assert.equal(result.nodes.length, before.nodes.length + 8); assert.deepEqual(graph, before); });
test("exact build input is enforced", () => expectCode(() => buildCanonicalAdmissionPlanV01({}), "INVALID_CANONICAL_ADMISSION_INPUT"));
test("policy precedence is enforced", () => expectCode(() => buildCanonicalAdmissionPlanV01({ graph: acceptedGraph(), plan: allPlan(), policyVersion: "bad", authorizedCandidateIds: [] }), "INVALID_ADMISSION_POLICY_VERSION"));
test("Graph errors are wrapped", () => { const graph = acceptedGraph(); graph.nodes[0].scope.userId = ""; expectCode(() => build(graph, allPlan(), []), "INVALID_CONTEXT_GRAPH"); });
test("Import Plan errors are wrapped", () => { const plan = structuredClone(allPlan()); plan.candidates.pop(); expectCode(() => build(acceptedGraph(), plan, []), "INVALID_IMPORT_PLAN"); });

for (const [name, mutate, code] of [
  ["missing target", plan => { plan.target.projectId = "project:missing"; }, "TARGET_PROJECT_NOT_FOUND"],
  ["non-project target", plan => { plan.target.projectId = "evidence:existing"; }, "TARGET_PROJECT_INVALID"],
  ["scope key", plan => { plan.target.scopeKey = "other"; }, "TARGET_SCOPE_UNSUPPORTED"]
]) test(`target boundary ${name}`, () => { const graph = acceptedGraph(); if (name === "non-project target") graph.nodes.push({ ...graph.nodes.find(n => n.kind === "evidence"), id: "evidence:existing" }); const plan = structuredClone(allPlan()); mutate(plan); expectCode(() => build(graph, plan, []), code); });
test("missing territory is target-invalid", () => { const graph = acceptedGraph(); delete graph.nodes.find(n => n.kind === "project").scope.territoryId; expectCode(() => build(graph, allPlan(), []), "TARGET_PROJECT_INVALID"); });
test("untrimmed non-empty target scope is target-invalid", () => { const graph = acceptedGraph(); graph.nodes.find(n => n.kind === "project").scope.userId = " user:self "; expectCode(() => build(graph, allPlan(), []), "TARGET_PROJECT_INVALID"); });
test("mismatched Project scope projectId is target-invalid", () => { const graph = acceptedGraph(); graph.nodes.find(n => n.kind === "project").scope.projectId = "project:other"; expectCode(() => build(graph, allPlan(), []), "TARGET_PROJECT_INVALID"); });
test("extra Project scope key is target-invalid", () => { const graph = acceptedGraph(); graph.nodes.find(n => n.kind === "project").scope.extra = true; expectCode(() => build(graph, allPlan(), []), "TARGET_PROJECT_INVALID"); });
test("empty userId remains generic Graph error", () => { const graph = acceptedGraph(); graph.nodes.find(n => n.kind === "project").scope.userId = ""; expectCode(() => build(graph, allPlan(), []), "INVALID_CONTEXT_GRAPH"); });

test("malformed authorization is rejected", () => expectCode(() => build(acceptedGraph(), allPlan(), "bad"), "INVALID_AUTHORIZATION_SELECTION"));
test("duplicate authorization is rejected", () => { const plan = allPlan(); expectCode(() => build(acceptedGraph(), plan, [plan.candidates[0].candidateId, plan.candidates[0].candidateId]), "INVALID_AUTHORIZATION_SELECTION"); });
test("unknown authorization is rejected", () => expectCode(() => build(acceptedGraph(), allPlan(), ["candidate:evidence:github:repo:unknown/x"]), "CANDIDATE_NOT_FOUND"));
test("authorization order is deterministic", () => { const plan = allPlan(); const ids = allIds(plan); assert.deepEqual(build(acceptedGraph(), plan, ids), build(acceptedGraph(), plan, [...ids].reverse())); });
test("partial authorization creates deferred decisions", () => { const plan = allPlan(); const admission = build(acceptedGraph(), plan, [plan.candidates[0].candidateId]); assert.deepEqual(admission.diagnostics, { candidateCount: 8, authorizedCount: 1, deferredCount: 7, proposalCount: 1, insertCount: 1, noopCount: 0, conflictCount: 0, applyAllowed: true }); });
test("empty authorization creates all deferred", () => { const admission = build(acceptedGraph(), allPlan(), []); assert.equal(admission.diagnostics.deferredCount, 8); assert.equal(admission.nodeProposals.length, 0); });
test("insert noop conflict decisions are deterministic", () => { const plan = allPlan(); const first = plan.candidates[0].candidateId; const initial = build(acceptedGraph(), plan, [first]); const graph = apply(acceptedGraph(), plan, initial, [first]); const noop = build(graph, plan, [first]); assert.equal(noop.decisions[0].disposition, "noop"); const tampered = structuredClone(graph); tampered.nodes.find(n => n.id === initial.nodeProposals[0].id).summary = "different"; const conflict = build(tampered, plan, [first]); assert.equal(conflict.decisions[0].disposition, "conflict"); });
test("caller inputs remain unchanged and output is frozen", () => { const graph = acceptedGraph(); const plan = allPlan(); const ids = allIds(plan); const graphBefore = structuredClone(graph); const planBefore = structuredClone(plan); const admission = build(graph, plan, ids); assert.deepEqual(graph, graphBefore); assert.deepEqual(plan, planBefore); assert.equal(Object.isFrozen(graph), false); assert.ok(Object.isFrozen(admission)); });

test("Apply exact input is enforced", () => expectCode(() => applyCanonicalAdmissionPlanV01({}), "INVALID_CANONICAL_ADMISSION_INPUT"));
test("Apply Graph-first precedence", () => { const graph = acceptedGraph(); graph.nodes.find(n => n.kind === "project").scope.userId = ""; const plan = allPlan(); const admission = build(acceptedGraph(), plan, []); expectCode(() => apply(graph, plan, admission, []), "INVALID_CONTEXT_GRAPH"); });
test("Apply preserves Admission validator error", () => { const plan = allPlan(); const admission = structuredClone(build(acceptedGraph(), plan, [])); delete admission.admissionVersion; expectCode(() => apply(acceptedGraph(), plan, admission, []), "CANONICAL_ADMISSION_PLAN_INVALID"); });
test("Apply malformed and unknown authorization errors", () => { const plan = allPlan(); const admission = build(acceptedGraph(), plan, []); expectCode(() => apply(acceptedGraph(), plan, admission, "bad"), "INVALID_AUTHORIZATION_SELECTION"); expectCode(() => apply(acceptedGraph(), plan, admission, ["candidate:evidence:github:repo:unknown/x"]), "CANDIDATE_NOT_FOUND"); });
test("Apply sourcePlan tamper", () => { const plan = allPlan(); const admission = structuredClone(build(acceptedGraph(), plan, allIds(plan))); admission.sourcePlan.generatedAt = "2026-08-07T13:00:00Z"; expectCode(() => apply(acceptedGraph(), plan, admission, allIds(plan)), "CANONICAL_ADMISSION_PLAN_INVALID"); });
test("Apply target descriptor tamper", () => { const plan = allPlan(); const admission = structuredClone(build(acceptedGraph(), plan, allIds(plan))); admission.target.projectId = "project:other"; expectCode(() => apply(acceptedGraph(), plan, admission, allIds(plan)), "CANONICAL_ADMISSION_PLAN_INVALID"); });
for (const [name, mutate] of [["title", p => { p.title = "tampered"; }], ["summary", p => { p.summary = "tampered"; p.payload.claim = "tampered"; }], ["payload", p => { p.payload.result = "tampered"; }], ["provenance", p => { p.provenance.authority = "tampered"; }], ["scope", p => { p.scope.projectId = "project:other"; }]]) test(`Apply ${name} binding`, () => { const plan = allPlan(); const ids = allIds(plan); const admission = structuredClone(build(acceptedGraph(), plan, ids)); mutate(admission.nodeProposals[0]); expectCode(() => apply(acceptedGraph(), plan, admission, ids), "CANONICAL_ADMISSION_SOURCE_MISMATCH"); });
test("Apply authorization deferred to insert tamper", () => { const plan = allPlan(); const admission = structuredClone(build(acceptedGraph(), plan, [])); const first = admission.decisions[0]; first.disposition = "insert"; first.reason = "authorized-new-observation"; admission.nodeProposals.push(build(acceptedGraph(), plan, [plan.candidates[0].candidateId]).nodeProposals[0]); admission.diagnostics.deferredCount = 7; admission.diagnostics.authorizedCount = 1; admission.diagnostics.proposalCount = 1; admission.diagnostics.insertCount = 1; expectCode(() => apply(acceptedGraph(), plan, admission, []), "CANONICAL_ADMISSION_AUTHORIZATION_MISMATCH"); });
test("Apply authorization insert to deferred tamper", () => { const plan = allPlan(); const ids = [plan.candidates[0].candidateId]; const admission = structuredClone(build(acceptedGraph(), plan, ids)); admission.decisions[0].disposition = "deferred"; admission.decisions[0].reason = "not-authorized"; admission.nodeProposals = []; admission.diagnostics.authorizedCount = 0; admission.diagnostics.deferredCount = 8; admission.diagnostics.proposalCount = 0; admission.diagnostics.insertCount = 0; expectCode(() => apply(acceptedGraph(), plan, admission, ids), "CANONICAL_ADMISSION_AUTHORIZATION_MISMATCH"); });

test("planned insert current missing appends", () => { const plan = allPlan(); const admission = build(acceptedGraph(), plan, allIds(plan)); const result = apply(acceptedGraph(), plan, admission, allIds(plan)); assert.equal(result.nodes.length, 38); });
test("planned insert current identical is noop", () => { const plan = allPlan(); const admission = build(acceptedGraph(), plan, allIds(plan)); const graph = apply(acceptedGraph(), plan, admission, allIds(plan)); const again = build(graph, plan, allIds(plan)); const result = apply(graph, plan, again, allIds(plan)); assert.equal(result.nodes.length, graph.nodes.length); });
test("planned insert current different conflicts", () => { const plan = allPlan(); const admission = build(acceptedGraph(), plan, allIds(plan)); const graph = acceptedGraph(); graph.nodes.push({ ...admission.nodeProposals[0], summary: "different", payload: { ...admission.nodeProposals[0].payload, claim: "different" } }); expectCode(() => apply(graph, plan, admission, allIds(plan)), "CANONICAL_APPLY_CONFLICT"); });
test("planned noop current missing conflicts", () => { const plan = allPlan(); const admission = build(acceptedGraph(), plan, [plan.candidates[0].candidateId]); const applied = apply(acceptedGraph(), plan, admission, [plan.candidates[0].candidateId]); const rebuilt = build(applied, plan, [plan.candidates[0].candidateId]); const missing = structuredClone(applied); missing.nodes = missing.nodes.filter(node => node.id !== rebuilt.nodeProposals[0].id); expectCode(() => apply(missing, plan, rebuilt, [plan.candidates[0].candidateId]), "CANONICAL_APPLY_CONFLICT"); });
test("planned noop current different conflicts", () => { const plan = allPlan(); const ids = [plan.candidates[0].candidateId]; const admission = build(acceptedGraph(), plan, ids); const applied = apply(acceptedGraph(), plan, admission, ids); const rebuilt = build(applied, plan, ids); const changed = structuredClone(applied); changed.nodes.find(n => n.id === rebuilt.nodeProposals[0].id).summary = "different"; expectCode(() => apply(changed, plan, rebuilt, ids), "CANONICAL_APPLY_CONFLICT"); });
test("planned conflict always conflicts", () => { const plan = allPlan(); const ids = [plan.candidates[0].candidateId]; const graph = acceptedGraph(); const first = build(graph, plan, ids); graph.nodes.push(first.nodeProposals[0]); const conflictGraph = structuredClone(graph); conflictGraph.nodes.find(n => n.id === first.nodeProposals[0].id).summary = "different"; const conflictPlan = build(conflictGraph, plan, ids); expectCode(() => apply(acceptedGraph(), plan, conflictPlan, ids), "CANONICAL_APPLY_CONFLICT"); });
test("atomic failure leaves caller Graph unchanged", () => { const plan = allPlan(); const ids = allIds(plan); const admission = structuredClone(build(acceptedGraph(), plan, ids)); admission.decisions[0].canonicalNodeId = "bad"; const graph = acceptedGraph(); const before = structuredClone(graph); expectCode(() => apply(graph, plan, admission, ids), "CANONICAL_NODE_ID_INVALID"); assert.deepEqual(graph, before); });
test("successful application preserves metadata edges package and Project", () => { const plan = allPlan(); const graph = acceptedGraph(); const before = structuredClone(graph); const result = apply(graph, plan, build(graph, plan, allIds(plan)), allIds(plan)); assert.deepEqual(result.metadata, before.metadata); assert.deepEqual(result.edges, before.edges); assert.deepEqual(result.contextPackage, before.contextPackage); assert.deepEqual(result.nodes.find(n => n.kind === "project"), before.nodes.find(n => n.kind === "project")); });
test("result is frozen while caller remains unfrozen", () => { const plan = allPlan(); const graph = acceptedGraph(); const result = apply(graph, plan, build(graph, plan, allIds(plan)), allIds(plan)); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.nodes[0])); assert.equal(Object.isFrozen(graph), false); });
test("reapply is idempotent", () => { const plan = allPlan(); const ids = allIds(plan); const first = apply(acceptedGraph(), plan, build(acceptedGraph(), plan, ids), ids); const secondAdmission = build(first, plan, ids); assert.equal(secondAdmission.diagnostics.noopCount, 8); const second = apply(first, plan, secondAdmission, ids); assert.deepEqual(second, first); });
test("new capture preserves history", () => { const firstPlan = planWithCapture(["repository", "branch", "commit"], "2026-08-07T12:00:00Z"); const secondPlan = planWithCapture(["repository", "branch", "commit"], "2026-08-08T12:00:00Z"); const firstCommit = candidateOf(firstPlan, "commit"); const secondCommit = candidateOf(secondPlan, "commit"); const graph = acceptedGraph(); const first = apply(graph, firstPlan, build(graph, firstPlan, [firstCommit.candidateId]), [firstCommit.candidateId]); const second = apply(first, secondPlan, build(first, secondPlan, [secondCommit.candidateId]), [secondCommit.candidateId]); const firstId = build(graph, firstPlan, [firstCommit.candidateId]).nodeProposals[0].id; const secondId = build(first, secondPlan, [secondCommit.candidateId]).nodeProposals[0].id; assert.ok(second.nodes.some(n => n.id === firstId)); assert.ok(second.nodes.some(n => n.id === secondId)); assert.notEqual(firstId, secondId); });
