import test from "node:test";
import assert from "node:assert/strict";
import example from "../examples/nexus-atlas-canonical-admission-v0.1.json" with { type: "json" };
import { CanonicalAdmissionError, CANONICAL_ADMISSION_ERROR_CODES_V01, canonicalNodeIdForCandidate, deepEqual, validateCanonicalAdmissionPlanV01 } from "../experience/context-v02/canonical-admission-validator.mjs";

const base = () => structuredClone(example.admissionPlan);
function expectCode(fn, code) { assert.throws(fn, error => error instanceof CanonicalAdmissionError && error.code === code && error.retryable === false); }
function invalidPlan(mutate, code = "CANONICAL_ADMISSION_PLAN_INVALID") { test(`validator boundary ${code} ${String(mutate).slice(0, 30)}`, () => { const plan = base(); mutate(plan); expectCode(() => validateCanonicalAdmissionPlanV01(plan), code); }); }

test("validator returns a frozen clone and leaves caller mutable", () => { const input = base(); const output = validateCanonicalAdmissionPlanV01(input); assert.notEqual(output, input); assert.ok(Object.isFrozen(output)); assert.ok(Object.isFrozen(output.nodeProposals[0])); assert.equal(Object.isFrozen(input), false); input.target.projectId = "project:nexus-atlas"; });
test("validator accepts accepted plan", () => assert.equal(validateCanonicalAdmissionPlanV01(base()).decisions.length, 8));
test("deepEqual ignores object insertion order", () => assert.equal(deepEqual({ a: 1, b: { c: 2 } }, { b: { c: 2 }, a: 1 }), true));
test("deepEqual distinguishes objects and primitives", () => {
  assert.equal(deepEqual({}, {}), true);
  assert.equal(deepEqual({}, 5), false);
  assert.equal(deepEqual({}, null), false);
  assert.equal(deepEqual({}, "x"), false);
  assert.equal(deepEqual({ a: {} }, { a: 5 }), false);
  assert.equal(deepEqual({ a: null }, { a: {} }), false);
  assert.equal(deepEqual([], {}), false);
  assert.equal(deepEqual({ a: { b: [] } }, { a: { b: [] } }), true);
  assert.equal(deepEqual({ z: 1, a: 2 }, { a: 2, z: 1 }), true);
});
test("canonical ID formula is deterministic", () => assert.equal(canonicalNodeIdForCandidate(example.admissionPlan.decisions[0].candidateId, example.admissionPlan.generatedAt), example.admissionPlan.decisions[0].canonicalNodeId));
test("error vocabulary is exact", () => assert.deepEqual(CANONICAL_ADMISSION_ERROR_CODES_V01.length, 16));
test("unknown error code is TypeError", () => assert.throws(() => new CanonicalAdmissionError("NOPE"), TypeError));

for (const key of ["admissionVersion", "policyVersion", "generatedAt", "sourcePlan", "target", "decisions", "nodeProposals", "diagnostics"]) invalidPlan(plan => { delete plan[key]; });
invalidPlan(plan => { plan.extra = true; });
invalidPlan(plan => { plan.admissionVersion = "0.2"; });
invalidPlan(plan => { plan.policyVersion = "other"; });
invalidPlan(plan => { plan.generatedAt = "2026-08-07T12:00:00"; });
invalidPlan(plan => { plan.generatedAt = "not-a-time"; });
for (const value of ["2026-02-30T12:00:00Z", "2026-04-31T12:00:00Z", "2026-00-10T12:00:00Z", "2026-13-01T12:00:00Z", "2026-08-07T24:00:00Z", "2026-08-07T12:60:00Z", "2026-08-07T12:00:60Z", "2026-08-07T12:00:00+24:00"]) invalidPlan(plan => { plan.generatedAt = value; });
invalidPlan(plan => { plan.sourcePlan.generatedAt = "2026-08-07T12:00:01Z"; });
for (const key of ["planVersion", "policyVersion", "generatedAt", "candidateIds"]) invalidPlan(plan => { delete plan.sourcePlan[key]; });
invalidPlan(plan => { plan.sourcePlan.extra = true; });
invalidPlan(plan => { plan.sourcePlan.planVersion = "0.2"; });
invalidPlan(plan => { plan.sourcePlan.policyVersion = "other"; });
invalidPlan(plan => { plan.sourcePlan.candidateIds = [plan.sourcePlan.candidateIds[0]]; });
invalidPlan(plan => { plan.sourcePlan.candidateIds[1] = plan.sourcePlan.candidateIds[0]; });
invalidPlan(plan => { plan.sourcePlan.candidateIds[0] = " candidate:evidence:github:a/b"; });
invalidPlan(plan => { plan.sourcePlan.candidateIds[0] = "candidate:evidence:other:a"; });
for (const key of ["projectId", "scopeKey"]) invalidPlan(plan => { delete plan.target[key]; });
invalidPlan(plan => { plan.target.extra = true; });
invalidPlan(plan => { plan.target.scopeKey = "other"; });
invalidPlan(plan => { plan.target.projectId = " project:nexus-atlas"; });
invalidPlan(plan => { plan.decisions = "bad"; });
invalidPlan(plan => { plan.decisions[0].extra = true; });
invalidPlan(plan => { plan.decisions[0].candidateId = plan.decisions[1].candidateId; });
invalidPlan(plan => { plan.decisions[0].disposition = "bad"; });
invalidPlan(plan => { plan.decisions[0].reason = "not-authorized"; });
invalidPlan(plan => { plan.decisions.reverse(); });
invalidPlan(plan => { plan.decisions[0].canonicalNodeId = "bad"; }, "CANONICAL_NODE_ID_INVALID");
invalidPlan(plan => { plan.nodeProposals[0].extra = true; });
invalidPlan(plan => { plan.nodeProposals[0].kind = "project"; });
invalidPlan(plan => { plan.nodeProposals[0].id = "other"; }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
invalidPlan(plan => { plan.nodeProposals[0].title = ""; });
invalidPlan(plan => { plan.nodeProposals[0].summary = "other"; });
invalidPlan(plan => { delete plan.nodeProposals[0].scope.territoryId; });
invalidPlan(plan => { plan.nodeProposals[0].scope.extra = true; });
invalidPlan(plan => { plan.nodeProposals[0].lifecycle.state = "inactive"; });
invalidPlan(plan => { plan.nodeProposals[0].lifecycle.createdAt = "2026-08-07T12:00:01Z"; });
invalidPlan(plan => { plan.nodeProposals[0].epistemic.verification = "inferred"; });
invalidPlan(plan => { plan.nodeProposals[0].epistemic.confidence = 0.5; });
invalidPlan(plan => { plan.nodeProposals[0].epistemic.freshness = "current"; });
invalidPlan(plan => { plan.nodeProposals[0].governance.sensitivity = "public"; });
invalidPlan(plan => { plan.nodeProposals[0].governance.requiresConfirmation = true; });
invalidPlan(plan => { plan.nodeProposals[0].provenance.provider = "other"; });
invalidPlan(plan => { plan.nodeProposals[0].provenance.capturedAt = "2026-08-07T12:00:01Z"; });
invalidPlan(plan => { plan.nodeProposals[0].provenance.reference = ""; });
invalidPlan(plan => { plan.nodeProposals[0].payload.claim = ""; });
invalidPlan(plan => { plan.nodeProposals[0].payload.observedAt = "bad"; });
invalidPlan(plan => { plan.nodeProposals[0].payload.observedAt = "2026-02-30T12:00:00Z"; });
invalidPlan(plan => { plan.nodeProposals[0].payload.appliesToVersion = "v1"; });
invalidPlan(plan => { plan.nodeProposals[0].payload.verificationMethod = "other"; });
invalidPlan(plan => { plan.nodeProposals[0].payload.result = ""; });
invalidPlan(plan => { plan.nodeProposals[0].payload.extra = true; });
invalidPlan(plan => { plan.nodeProposals.pop(); }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
invalidPlan(plan => { plan.nodeProposals.push(structuredClone(plan.nodeProposals[0])); }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
invalidPlan(plan => { plan.nodeProposals.reverse(); }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
invalidPlan(plan => { plan.decisions[0].disposition = "deferred"; plan.decisions[0].reason = "not-authorized"; }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
for (const key of ["candidateCount", "authorizedCount", "deferredCount", "proposalCount", "insertCount", "noopCount", "conflictCount", "applyAllowed"]) invalidPlan(plan => { delete plan.diagnostics[key]; });
invalidPlan(plan => { plan.diagnostics.extra = true; });
invalidPlan(plan => { plan.diagnostics.candidateCount = 1; }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
invalidPlan(plan => { plan.diagnostics.authorizedCount = 1; }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
invalidPlan(plan => { plan.diagnostics.applyAllowed = false; }, "CANONICAL_ADMISSION_COVERAGE_MISMATCH");
