import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildGeneralizedContextPackage, GeneralizedContextPackageError } from "../experience/context-v03/generalized-context-package-builder.mjs";
import { createFullSyntheticGraph, createFullSyntheticLedger, createBaseRecord, createEvidenceNode, GENERATED_AT } from "./helpers/generalized-context-package-fixtures.mjs";

function valid() { const graph = createFullSyntheticGraph(); const ledger = createFullSyntheticLedger(); return { graph, ledger, projectId: "project:alpha", scopeKey: "project:alpha", generatedAt: GENERATED_AT }; }
function build() { return buildGeneralizedContextPackage(valid()); }
function expectCode(fn, code) { assert.throws(fn, (error) => error instanceof GeneralizedContextPackageError && error.code === code); }

test("builder returns the accepted top-level package", () => { const p = build(); assert.deepEqual(Object.keys(p), ["packageVersion", "packageId", "generatedAt", "scope", "project", "identity", "goals", "decisions", "memories", "evidence", "records", "risks", "actions", "conflicts", "omissions", "sourceSummary"]); });
test("invalid graph maps validator failure", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), graph: {} }), "INVALID_GRAPH"));
test("invalid ledger maps structure failure", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), ledger: null }), "INVALID_LEDGER"));
test("invalid project id", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), projectId: "" }), "INVALID_PROJECT_ID"));
test("invalid scope key", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), scopeKey: "" }), "INVALID_SCOPE_KEY"));
test("invalid generatedAt", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), generatedAt: "2026-08-05" }), "INVALID_GENERATED_AT"));
test("project not found", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), projectId: "project:missing", scopeKey: "project:missing", ledger: createFullSyntheticLedger({ projectId: "project:missing" }) }), "PROJECT_NOT_FOUND"));
test("project kind mismatch", () => { const v = valid(); v.projectId = "decision:alpha-effective"; v.scopeKey = "decision:alpha-effective"; v.ledger.projectId = v.projectId; expectCode(() => buildGeneralizedContextPackage(v), "PROJECT_KIND_MISMATCH"); });
test("project eligibility", () => { const v = valid(); v.graph.nodes[0].lifecycle.state = "archived"; expectCode(() => buildGeneralizedContextPackage(v), "PROJECT_NOT_ELIGIBLE"); });
test("ledger version mismatch", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), ledger: createFullSyntheticLedger({ ledgerVersion: "0.1" }) }), "LEDGER_VERSION_MISMATCH"));
test("ledger project mismatch", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), ledger: createFullSyntheticLedger({ projectId: "project:beta" }) }), "LEDGER_PROJECT_MISMATCH"));
test("ledger generatedAt mismatch", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), ledger: createFullSyntheticLedger({ generatedAt: "2026-08-05T10:00:00+08:00" }) }), "LEDGER_GENERATED_AT_MISMATCH"));
test("ledger scope mismatch", () => { const v = valid(); v.ledger.effectiveDecisions[0].scopeKey = "project:beta"; expectCode(() => buildGeneralizedContextPackage(v), "LEDGER_SCOPE_MISMATCH"); });
test("missing package reference", () => { const v = valid(); v.ledger.effectiveDecisions[0].id = "decision:missing"; expectCode(() => buildGeneralizedContextPackage(v), "PACKAGE_REFERENCE_MISSING"); });
test("package reference kind mismatch", () => { const v = valid(); v.ledger.effectiveDecisions[0].id = "memory:alpha-inherited"; expectCode(() => buildGeneralizedContextPackage(v), "PACKAGE_REFERENCE_KIND_MISMATCH"); });
test("package reference scope mismatch", () => { const v = valid(); v.graph.nodes.find((n) => n.id === "decision:alpha-effective").scope.projectId = "project:beta"; expectCode(() => buildGeneralizedContextPackage(v), "PACKAGE_REFERENCE_SCOPE_MISMATCH"); });
test("restricted package reference", () => { const v = valid(); v.graph.nodes.find((n) => n.id === "decision:alpha-effective").governance.sensitivity = "restricted"; expectCode(() => buildGeneralizedContextPackage(v), "PACKAGE_REFERENCE_RESTRICTED"); });
test("strict ISO rejects date-only", () => expectCode(() => buildGeneralizedContextPackage({ ...valid(), generatedAt: "2026-08-05" }), "INVALID_GENERATED_AT"));
test("graph input is unchanged", () => { const v = valid(); const before = structuredClone(v.graph); buildGeneralizedContextPackage(v); assert.deepEqual(v.graph, before); });
test("ledger input is unchanged", () => { const v = valid(); const before = structuredClone(v.ledger); buildGeneralizedContextPackage(v); assert.deepEqual(v.ledger, before); });
test("returned records are isolated", () => { const v = valid(); const p = buildGeneralizedContextPackage(v); assert.notStrictEqual(p.project, v.graph.nodes[0]); assert.notStrictEqual(p.decisions.effective[0], v.graph.nodes[1]); });
test("lifecycle is a string in every full projection", () => { const p = build(); const records = [...p.decisions.effective, ...p.decisions.proposed, ...p.memories.inherited, ...p.memories.inferred, ...p.memories.disputed, ...p.memories.historical, ...p.evidence.current, ...p.evidence.inferred, ...p.evidence.disputed, ...p.evidence.historical, ...p.records.disputed, ...p.records.historical, ...p.risks.open, ...p.actions.next]; assert.ok(records.every((r) => typeof r.lifecycle === "string")); });
test("Windows reference is cleared", () => { const v = valid(); v.graph.nodes[0].provenance.reference = "C:\\private\\source"; assert.equal(buildGeneralizedContextPackage(v).project.source.reference, null); });
test("UNC reference is cleared", () => { const v = valid(); v.graph.nodes[0].provenance.reference = "\\\\server\\share"; assert.equal(buildGeneralizedContextPackage(v).project.source.reference, null); });
test("POSIX reference is cleared", () => { const v = valid(); v.graph.nodes[0].provenance.reference = "/home/private/source"; assert.equal(buildGeneralizedContextPackage(v).project.source.reference, null); });
test("all POSIX absolute references are cleared", () => { for (const reference of ["/tmp", "/etc", "/var/data", "/home/user/file", "/Users/name/file"]) { const v = valid(); v.graph.nodes[0].provenance.reference = reference; assert.equal(buildGeneralizedContextPackage(v).project.source.reference, null, reference); } });
test("repository and documentation references remain", () => { for (const reference of ["README.md", "docs/file.md", "owner/repository", "https://example.com/file"]) { const v = valid(); v.graph.nodes[0].provenance.reference = reference; assert.equal(buildGeneralizedContextPackage(v).project.source.reference, reference, reference); } });
test("file reference is cleared", () => { const v = valid(); v.graph.nodes[0].provenance.reference = "file:///private/source"; assert.equal(buildGeneralizedContextPackage(v).project.source.reference, null); });
test("repository reference remains", () => assert.equal(build().project.source.reference, "fixture:project:alpha"));
test("missing non-DM provenance creates omission", () => { const v = valid(); v.graph.nodes.find((n) => n.id === "risk:alpha-open").provenance.authority = ""; const p = buildGeneralizedContextPackage(v); assert.ok(p.omissions.some((o) => o.id === "risk:alpha-open" && o.rule === "provenance-insufficient")); });
test("restricted omission wins priority", () => { const v = valid(); const n = v.graph.nodes.find((x) => x.id === "milestone:alpha-disputed"); n.governance.sensitivity = "restricted"; n.governance.inheritance = "never"; const p = buildGeneralizedContextPackage(v); assert.equal(p.omissions.find((o) => o.id === n.id).rule, "restricted"); });
test("out-of-scope record is not an omission", () => { const v = valid(); v.graph.nodes.push({ ...v.graph.nodes.find((n) => n.id === "risk:alpha-open"), id: "risk:beta-open", scope: { ...v.graph.nodes.find((n) => n.id === "risk:alpha-open").scope, projectId: "project:beta" } }); const p = buildGeneralizedContextPackage(v); assert.ok(!p.omissions.some((o) => o.id === "risk:beta-open")); });
test("completed current milestone is not historical", () => { const p = build(); assert.ok(!p.records.historical.some((r) => r.id === "milestone:alpha-disputed")); });
test("stale risk is historical", () => { const v = valid(); const n = v.graph.nodes.find((x) => x.id === "risk:alpha-open"); n.epistemic.freshness = "stale"; const p = buildGeneralizedContextPackage(v); assert.ok(p.records.historical.some((r) => r.id === n.id)); });
test("disputed action is disputed record", () => { const v = valid(); const n = v.graph.nodes.find((x) => x.id === "action:alpha-next"); n.epistemic.verification = "disputed"; const p = buildGeneralizedContextPackage(v); assert.ok(p.records.disputed.some((r) => r.id === n.id)); });
test("historical Decision remains only in chain", () => { const p = build(); assert.ok(!p.records.historical.some((r) => r.kind === "decision")); assert.ok(p.decisions.chains[0].orderedDecisionIds.includes("decision:alpha-history")); });
test("Memory classification follows Ledger", () => { const p = build(); assert.deepEqual(p.memories.inherited.map((x) => x.id), ["memory:alpha-inherited"]); assert.deepEqual(p.memories.inferred.map((x) => x.id), ["memory:alpha-inferred"]); });
test("summary counts chain history", () => { const p = build(); assert.equal(p.sourceSummary.byKind.decision, 3); });
test("summary counts conflict references", () => { const v = valid(); v.ledger.unresolvedConflicts = [{ conflictId: "conflict:alpha-memory", type: "memory_statement_conflict", subjectKey: "memory", scopeKey: "project:alpha", recordIds: ["memory:alpha-disputed"], explanation: "Conflict", autoResolvable: false, requiredResolution: "human" }]; assert.equal(buildGeneralizedContextPackage(v).sourceSummary.byKind.memory, 4); });
test("same id in chain and section counts once", () => { const p = build(); assert.equal(p.sourceSummary.totalIncludedRecords, 16); });
test("package shape has no internal fields", () => { const p = build(); assert.equal("rawGraph" in p, false); assert.equal("rawLedger" in p, false); assert.equal("diagnostics" in p, false); });
test("does not call global network", () => { const old = globalThis.fetch; globalThis.fetch = () => { throw new Error("unexpected"); }; try { assert.doesNotThrow(build); } finally { globalThis.fetch = old; } });
test("does not call Date.now", () => { const old = Date.now; Date.now = () => { throw new Error("unexpected"); }; try { assert.doesNotThrow(build); } finally { Date.now = old; } });
test("does not call Math.random", () => { const old = Math.random; Math.random = () => { throw new Error("unexpected"); }; try { assert.doesNotThrow(build); } finally { Math.random = old; } });
test("module uses no environment state", () => { const source = readFileSync(new URL("../experience/context-v03/generalized-context-package-builder.mjs", import.meta.url), "utf8"); assert.equal(source.includes("process.env"), false); });
test("source summary keys are sorted", () => { const p = build(); assert.deepEqual(Object.keys(p.sourceSummary.providers), [...Object.keys(p.sourceSummary.providers)].sort()); assert.deepEqual(Object.keys(p.sourceSummary.byKind), [...Object.keys(p.sourceSummary.byKind)].sort()); });
test("output is deeply frozen", () => { const p = build(); assert.equal(Object.isFrozen(p), true); assert.equal(Object.isFrozen(p.decisions.effective), true); });

test("active Goal with inheritance never is omitted before classification", () => { const v = valid(); v.graph.nodes.push(createBaseRecord("goal:alpha-never", "goal", { governance: { sensitivity: "public", inheritance: "never", requiresConfirmation: false } })); const p = buildGeneralizedContextPackage(v); assert.equal(p.goals.active.some((record) => record.id === "goal:alpha-never"), false); assert.equal(p.omissions.find((item) => item.id === "goal:alpha-never")?.rule, "inheritance-never"); });
test("active Risk with explicit only is omitted before classification", () => { const v = valid(); v.graph.nodes.push(createBaseRecord("risk:alpha-explicit", "risk", { governance: { sensitivity: "public", inheritance: "explicit_only", requiresConfirmation: false }, payload: { severity: "high", likelihood: "medium", mitigation: "Synthetic mitigation." } })); const p = buildGeneralizedContextPackage(v); assert.equal(p.risks.open.some((record) => record.id === "risk:alpha-explicit"), false); assert.equal(p.omissions.find((item) => item.id === "risk:alpha-explicit")?.rule, "explicit-only-no-consent"); });
test("active restricted Action is omitted before classification", () => { const v = valid(); v.graph.nodes.push(createBaseRecord("action:alpha-restricted", "action", { governance: { sensitivity: "restricted", inheritance: "project_only", requiresConfirmation: false }, payload: { description: "Sensitive", owner: "user:self", priority: "high", actionStatus: "ready", completionCriteria: "Never expose", relatedDecisionRefs: [], externalEffect: false, requiresConfirmation: false } })); const p = buildGeneralizedContextPackage(v); assert.equal(p.actions.next.some((record) => record.id === "action:alpha-restricted"), false); assert.equal(p.omissions.find((item) => item.id === "action:alpha-restricted")?.rule, "restricted"); });
test("inferred Identity without usable provenance is omitted before classification", () => { const v = valid(); v.graph.nodes.push(createBaseRecord("identity:alpha-inferred", "identity", { epistemic: { verification: "inferred", confidence: 0.5, freshness: "current" }, provenance: { provider: "fixture", reference: "/tmp/private", capturedAt: GENERATED_AT, retrievalMode: "fixture", authority: "fixture-authority" } })); const p = buildGeneralizedContextPackage(v); assert.equal(p.identity.inferred.some((record) => record.id === "identity:alpha-inferred"), false); assert.equal(p.omissions.find((item) => item.id === "identity:alpha-inferred")?.rule, "provenance-insufficient"); });
test("computed omissions are sorted independently of Graph order", () => { const v = valid(); const risk = (id) => createBaseRecord(id, "risk", { governance: { sensitivity: "public", inheritance: "never", requiresConfirmation: false }, payload: { severity: "high", likelihood: "medium", mitigation: "Synthetic mitigation." } }); v.graph.nodes.push(risk("risk:zeta"), risk("risk:alpha"), risk("risk:middle")); const reversed = structuredClone(v); reversed.graph.nodes.reverse(); assert.deepEqual(buildGeneralizedContextPackage(v), buildGeneralizedContextPackage(reversed)); const ids = buildGeneralizedContextPackage(v).omissions.filter((item) => item.rule === "inheritance-never").map((item) => item.id); assert.deepEqual(ids, ["risk:alpha", "risk:middle", "risk:zeta"]); });
test("chain projection is an allowlist and ordered IDs are first occurrence unique", () => { const v = valid(); v.ledger.decisionChains[0].orderedDecisionIds = ["decision:alpha-history", "decision:alpha-effective", "decision:alpha-history"]; v.ledger.decisionChains[0].internalResolverState = "must-not-project"; v.ledger.decisionChains[0].debugPayload = { secret: true }; const chain = buildGeneralizedContextPackage(v).decisions.chains[0]; assert.deepEqual(chain.orderedDecisionIds, ["decision:alpha-history", "decision:alpha-effective"]); assert.equal("internalResolverState" in chain, false); assert.equal("debugPayload" in chain, false); assert.deepEqual(Object.keys(chain), ["subjectKey", "scopeKey", "rootDecisionIds", "orderedDecisionIds", "terminalDecisionIds", "chainStatus"]); });
test("conflict projection is an allowlist and rejects non-DM references", () => { const v = valid(); v.ledger.unresolvedConflicts = [{ conflictId: "conflict:extra", type: "test", subjectKey: "alpha", scopeKey: "project:alpha", recordIds: ["decision:alpha-effective"], explanation: "Conflict", autoResolvable: false, requiredResolution: "human", debugPayload: { secret: true } }]; const conflict = buildGeneralizedContextPackage(v).conflicts.unresolved[0]; assert.equal("debugPayload" in conflict, false); assert.deepEqual(Object.keys(conflict), ["conflictId", "type", "subjectKey", "scopeKey", "recordIds", "explanation", "autoResolvable", "requiredResolution"]); const bad = structuredClone(v); bad.ledger.unresolvedConflicts[0].recordIds = ["evidence:alpha-current"]; assert.throws(() => buildGeneralizedContextPackage(bad), (error) => error.code === "PACKAGE_REFERENCE_KIND_MISMATCH"); });
test("duplicate conflicts require identical safe content", () => { const v = valid(); const conflict = { conflictId: "conflict:duplicate", type: "test", subjectKey: "alpha", scopeKey: "project:alpha", recordIds: ["decision:alpha-effective"], explanation: "Conflict", autoResolvable: false, requiredResolution: "human" }; v.ledger.unresolvedConflicts = [conflict, structuredClone(conflict)]; assert.equal(buildGeneralizedContextPackage(v).conflicts.unresolved.length, 1); const bad = structuredClone(v); bad.ledger.unresolvedConflicts[1].explanation = "Changed"; assert.throws(() => buildGeneralizedContextPackage(bad), (error) => error.code === "INVALID_LEDGER"); });
test("evidence sections sort by observedAt and then ID", () => { const v = valid(); const later = createEvidenceNode("evidence:zeta", { payload: { ...createEvidenceNode("evidence:tmp").payload, observedAt: "2026-08-06T00:00:00+08:00" } }); const earlier = createEvidenceNode("evidence:alpha", { payload: { ...createEvidenceNode("evidence:tmp").payload, observedAt: "2026-08-04T00:00:00+08:00" } }); v.graph.nodes.push(later, earlier); const p = buildGeneralizedContextPackage(v); assert.deepEqual(p.evidence.current.map((record) => record.id), ["evidence:alpha", "evidence:alpha-current", "evidence:zeta"]); });
test("completed current milestone is neither historical nor disputed", () => { const v = valid(); v.graph.nodes.push(createBaseRecord("milestone:alpha-completed-current", "milestone", { lifecycle: { state: "completed", createdAt: GENERATED_AT, updatedAt: GENERATED_AT } })); const p = buildGeneralizedContextPackage(v); assert.equal(p.records.historical.some((record) => record.id === "milestone:alpha-completed-current"), false); assert.equal(p.records.disputed.some((record) => record.id === "milestone:alpha-completed-current"), false); assert.equal(p.sourceSummary.totalIncludedRecords, 16); });
