import assert from "node:assert/strict";
import { test } from "node:test";
import { createGitHubSourceAdapter } from "../experience/source-v01/github-source-adapter.mjs";
import { createGitHubClientFixture, createRequestedLimits, CAPTURED_AT } from "./helpers/github-source-fixtures.mjs";
const input = { repositoryRef: "Cyrilla-Mist/Nexus-AI", requestedLimits: createRequestedLimits(), capturedAt: CAPTURED_AT };
test("adapter produces the accepted eight-record snapshot", async () => { const client = createGitHubClientFixture(); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(snapshot.records.length, 8); assert.deepEqual(client.calls.map(call => call[0]), ["repository", "branch", "commits", "issues", "pullRequests", "releases", "tags"]); });
test("zero collection limits skip corresponding client calls", async () => { const client = createGitHubClientFixture(); const limits = createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 0, tags: 0 }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: limits }); assert.deepEqual(client.calls.map(call => call[0]), ["repository", "branch"]); assert.equal(snapshot.records.length, 2); });
test("adapter projects a strict privacy allowlist and freezes output", async () => { const client = createGitHubClientFixture({ repository: { name: "nexus-ai", fullName: "cyrilla-mist/nexus-ai", defaultBranch: "main", archived: false, visibility: "public", updatedAt: "2026-08-07T11:00:00Z", token: "secret" } }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert(!JSON.stringify(snapshot).includes("token")); assert(Object.isFrozen(snapshot)); });
test("hard maximum and malformed inputs are rejected", async () => { const adapter = createGitHubSourceAdapter({ client: createGitHubClientFixture() }); await assert.rejects(() => adapter.readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 21 }) }), { code: "INVALID_ADAPTER_OPTIONS" }); await assert.rejects(() => adapter.readSnapshot({ ...input, capturedAt: "bad" }), { code: "INVALID_CAPTURED_AT" }); });
