import assert from "node:assert/strict";
import { test } from "node:test";
import { createGitHubSourceAdapter } from "../experience/source-v01/github-source-adapter.mjs";
import { createGitHubClientFixture, createRequestedLimits, CAPTURED_AT } from "./helpers/github-source-fixtures.mjs";
import { SourceAdapterError } from "../experience/source-v01/source-snapshot-validator.mjs";
const input = { repositoryRef: "Cyrilla-Mist/Nexus-AI", requestedLimits: createRequestedLimits(), capturedAt: CAPTURED_AT };
test("adapter produces the accepted eight-record snapshot", async () => { const client = createGitHubClientFixture(); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(snapshot.records.length, 8); assert.deepEqual(client.calls.map(call => call[0]), ["repository", "branch", "commits", "issues", "pullRequests", "releases", "tags"]); });
test("zero collection limits skip corresponding client calls", async () => { const client = createGitHubClientFixture(); const limits = createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 0, tags: 0 }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: limits }); assert.deepEqual(client.calls.map(call => call[0]), ["repository", "branch"]); assert.equal(snapshot.records.length, 2); });
test("adapter projects a strict privacy allowlist and freezes output", async () => { const client = createGitHubClientFixture({ repository: { name: "nexus-ai", fullName: "cyrilla-mist/nexus-ai", defaultBranch: "main", archived: false, visibility: "public", updatedAt: "2026-08-07T11:00:00Z", token: "secret" } }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert(!JSON.stringify(snapshot).includes("token")); assert(Object.isFrozen(snapshot)); });
test("hard maximum and malformed inputs are rejected", async () => { const adapter = createGitHubSourceAdapter({ client: createGitHubClientFixture() }); await assert.rejects(() => adapter.readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 21 }) }), { code: "INVALID_ADAPTER_OPTIONS" }); await assert.rejects(() => adapter.readSnapshot({ ...input, capturedAt: "bad" }), { code: "INVALID_CAPTURED_AT" }); });

test("adapter acceptance boundary has explicit independent subtests", async t => {
  const fixture = () => createGitHubClientFixture();
  const cases = [
    ["public API exposes adapter", async () => assert.equal(typeof createGitHubSourceAdapter({ client: fixture() }).readSnapshot, "function")],
    ["adapter is frozen", async () => assert(Object.isFrozen(createGitHubSourceAdapter({ client: fixture() })))],
    ["client is required", async () => assert.throws(() => createGitHubSourceAdapter(), { code: "INVALID_ADAPTER_OPTIONS" })],
    ["repository method is required", async () => assert.throws(() => createGitHubSourceAdapter({ client: {} }), { code: "INVALID_ADAPTER_OPTIONS" })],
    ["repositoryRef is explicit", async () => assert.rejects(() => createGitHubSourceAdapter({ client: fixture() }).readSnapshot({ requestedLimits: createRequestedLimits(), capturedAt: CAPTURED_AT }), { code: "INVALID_REPOSITORY_REF" })],
    ["limits are explicit", async () => assert.rejects(() => createGitHubSourceAdapter({ client: fixture() }).readSnapshot({ repositoryRef: "a/b", capturedAt: CAPTURED_AT }), { code: "INVALID_ADAPTER_OPTIONS" })],
    ["capture time is explicit", async () => assert.rejects(() => createGitHubSourceAdapter({ client: fixture() }).readSnapshot({ repositoryRef: "a/b", requestedLimits: createRequestedLimits() }), { code: "INVALID_CAPTURED_AT" })],
    ["positive offset capture accepted", async () => { const client = fixture(); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, capturedAt: "2026-08-07T20:00:00+08:00" }); assert.equal(snapshot.capturedAt, "2026-08-07T20:00:00+08:00"); }],
    ["repository is first call", async () => assert.equal(fixture().calls.length, 0)],
    ["core singleton calls", async () => { const client = fixture(); await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 0, tags: 0 }) }); assert.deepEqual(client.calls.map(call => call[0]), ["repository", "branch"]); }],
    ["fixed collection order", async () => { const client = fixture(); await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.deepEqual(client.calls.map(call => call[0]), ["repository", "branch", "commits", "issues", "pullRequests", "releases", "tags"]); }],
    ["mixed-case repository canonicalized", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.scope.repositoryRef, "cyrilla-mist/nexus-ai"); }],
    ["repository payload canonicalized", async () => { const client = fixture(); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(snapshot.records[0].payload.fullName, "cyrilla-mist/nexus-ai"); assert.equal(snapshot.records[0].payload.name, "nexus-ai"); }],
    ["default branch singleton", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records[1].sourceType, "branch"); }],
    ["branch mismatch rejected", async () => { const client = fixture(); client.getDefaultBranch = async () => ({ name: "other", headSha: "1".repeat(40) }); await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_RESPONSE_INVALID" }); }],
    ["repository mismatch rejected", async () => { const client = fixture(); client.getRepository = async () => ({ name: "other", fullName: "other/repo", defaultBranch: "main", archived: false, visibility: "public", updatedAt: "2026-08-07T11:00:00Z" }); await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_SCOPE_MISMATCH" }); }],
    ["zero limit skips commits", async () => { const client = fixture(); await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0 }) }); assert(!client.calls.some(call => call[0] === "commits")); }],
    ["all limits produce seven types", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(new Set(snapshot.records.map(record => record.sourceType)).size, 7); }],
    ["extra client method is not called", async () => { const client = fixture(); let called = false; client.write = () => { called = true; }; await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 0, tags: 0 }) }); assert.equal(called, false); }],
    ["write-like method is not called", async () => { const client = fixture(); client.pushCommit = () => { throw new Error("called"); }; await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(client.calls.some(call => call[0] === "pushCommit"), false); }],
    ["commit projection", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.deepEqual(Object.keys(snapshot.records.find(record => record.sourceType === "commit").payload), ["sha", "authoredAt", "committedAt", "messageHeadline"]); }],
    ["issue projection", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records.find(record => record.sourceType === "issue").payload.number, 17); }],
    ["PR never becomes issue", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records.find(record => record.sourceType === "pull_request").sourceType, "pull_request"); }],
    ["PR open state", async () => { const client = fixture(); client.listPullRequests = async () => ({ items: [{ number: 1, title: "open", state: "open", draft: false, merged: false, createdAt: "2026-08-01T00:00:00Z", updatedAt: "2026-08-07T12:00:00Z", closedAt: null, mergedAt: null, headSha: "4".repeat(40), baseRef: "main" }], pagesRead: 1, continuationAvailable: false }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 1, releases: 0, tags: 0 }) }); assert.equal(snapshot.records[2].observedState, "open"); }],
    ["PR closed state", async () => { const client = fixture(); client.listPullRequests = async () => ({ items: [{ number: 1, title: "closed", state: "closed", draft: false, merged: false, createdAt: "2026-08-01T00:00:00Z", updatedAt: "2026-08-07T12:00:00Z", closedAt: "2026-08-07T12:00:00Z", mergedAt: null, headSha: "4".repeat(40), baseRef: "main" }], pagesRead: 1, continuationAvailable: false }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 1, releases: 0, tags: 0 }) }); assert.equal(snapshot.records[2].observedState, "closed"); }],
    ["PR merged state", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records.find(record => record.sourceType === "pull_request").observedState, "merged"); }],
    ["PR observedAt uses updatedAt", async () => { const client = fixture(); client.listPullRequests = async () => ({ items: [{ number: 1, title: "merged", state: "closed", draft: false, merged: true, createdAt: "2026-08-01T00:00:00Z", updatedAt: "2026-08-07T12:00:00Z", closedAt: "2026-08-07T10:00:00Z", mergedAt: "2026-08-07T11:00:00Z", headSha: "4".repeat(40), baseRef: "main" }], pagesRead: 1, continuationAvailable: false }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 1, releases: 0, tags: 0 }) }); assert.equal(snapshot.records.find(record => record.sourceType === "pull_request").observedAt, "2026-08-07T12:00:00Z"); }],
    ["published release", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records.find(record => record.sourceType === "release").observedState, "published"); }],
    ["draft release", async () => { const client = fixture(); client.listReleases = async () => ({ items: [{ immutableId: "a", tagName: "a", name: "a", draft: true, prerelease: false, createdAt: "2026-08-01T00:00:00Z", publishedAt: null }], pagesRead: 1, continuationAvailable: false }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 1, tags: 0 }) }); assert.equal(snapshot.records[2].observedState, "draft"); }],
    ["prerelease release", async () => { const client = fixture(); client.listReleases = async () => ({ items: [{ immutableId: "a", tagName: "a", name: "a", draft: false, prerelease: true, createdAt: "2026-08-01T00:00:00Z", publishedAt: "2026-08-01T01:00:00Z" }], pagesRead: 1, continuationAvailable: false }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 1, tags: 0 }) }); assert.equal(snapshot.records[2].observedState, "prerelease"); }],
    ["tag projection", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records.find(record => record.sourceType === "tag").payload.name, "v0.1.0"); }],
    ["commit deterministic order", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); const commits = snapshot.records.filter(record => record.sourceType === "commit"); assert(commits[0].payload.committedAt > commits[1].payload.committedAt); }],
    ["issue deterministic order", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.records.filter(record => record.sourceType === "issue").length, 1); }],
    ["collection permutation normalized", async () => { const client = fixture(); const original = client.listCommits; client.listCommits = async input => { const result = await original(input); result.items.reverse(); return result; }; const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(snapshot.records[2].sourceType, "commit"); }],
    ["privacy excludes author email", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(!JSON.stringify(snapshot).includes("authorEmail")); }],
    ["privacy excludes bodies", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(!JSON.stringify(snapshot).includes("private")); }],
    ["canonical fields omitted", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(!JSON.stringify(snapshot).includes('"kind"')); }],
    ["truncated read remains complete", async () => { const client = fixture(); client.listCommits = async () => ({ items: [client.__item], pagesRead: 1, continuationAvailable: true }); const base = fixture(); const item = (await base.listCommits({})).items[0]; client.listCommits = async () => ({ items: [item, { ...item, sha: "6".repeat(40), committedAt: "2026-08-05T10:00:00Z" }], pagesRead: 1, continuationAvailable: true }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(snapshot.diagnostics.complete, true); assert.equal(snapshot.diagnostics.collections.commits.truncated, true); }],
    ["over-limit logical result rejected", async () => { const client = fixture(); const result = await client.listCommits({}); client.listCommits = async () => ({ ...result, items: [...result.items, { ...result.items[0], sha: "6".repeat(40) }] }); await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_RESPONSE_INVALID" }); }],
    ["incomplete pagination rejected", async () => { const client = fixture(); const result = await client.listCommits({}); client.listCommits = async () => ({ ...result, items: [result.items[0]], continuationAvailable: true }); await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_RESPONSE_INVALID" }); }],
    ["pagination page maximum enforced", async () => { const client = fixture(); const result = await client.listCommits({}); client.listCommits = async () => ({ ...result, pagesRead: 6, items: [result.items[0], result.items[1]] }); await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_PAGINATION_LIMIT" }); }],
    ["auth error maps safely", async () => { const client = fixture(); client.listIssues = async () => { throw new SourceAdapterError("SOURCE_AUTH_REQUIRED", "unsafe"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_AUTH_REQUIRED", retryable: false }); }],
    ["forbidden error maps", async () => { const client = fixture(); client.listIssues = async () => { throw new SourceAdapterError("SOURCE_FORBIDDEN"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_FORBIDDEN" }); }],
    ["not found error maps", async () => { const client = fixture(); client.listIssues = async () => { throw new SourceAdapterError("SOURCE_NOT_FOUND"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_NOT_FOUND" }); }],
    ["rate limit retryable", async () => { const client = fixture(); client.listIssues = async () => { throw new SourceAdapterError("SOURCE_RATE_LIMITED"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_RATE_LIMITED", retryable: true }); }],
    ["unavailable retryable", async () => { const client = fixture(); client.listIssues = async () => { throw new SourceAdapterError("SOURCE_UNAVAILABLE"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_UNAVAILABLE", retryable: true }); }],
    ["unknown client exception unavailable", async () => { const client = fixture(); client.listIssues = async () => { throw new Error("network detail"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), { code: "SOURCE_UNAVAILABLE" }); }],
    ["known error details safe", async () => { const client = fixture(); client.listIssues = async () => { throw new SourceAdapterError("SOURCE_FORBIDDEN", "token-secret", { token: "secret" }); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), error => error.code === "SOURCE_FORBIDDEN" && !JSON.stringify(error).includes("secret")); }],
    ["input unchanged", async () => { const client = fixture(); const original = structuredClone(input); await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.deepEqual(input, original); }],
    ["snapshot deeply frozen", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(Object.isFrozen(snapshot) && Object.isFrozen(snapshot.scope) && Object.isFrozen(snapshot.records[0].payload) && Object.isFrozen(snapshot.diagnostics.collections.commits)); }],
    ["source state available", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.source.state, "available"); }],
    ["no empty error snapshot", async () => { const client = fixture(); client.getRepository = async () => { throw new SourceAdapterError("SOURCE_NOT_FOUND"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), error => error instanceof SourceAdapterError && error.code === "SOURCE_NOT_FOUND"); }],
    ["diagnostics requested applied", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.diagnostics.collections.commits.requestedLimit, snapshot.diagnostics.collections.commits.appliedLimit); }],
    ["diagnostics items read exact", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert.equal(snapshot.diagnostics.collections.issues.itemsRead, 1); }],
    ["release null values allowed", async () => { const client = fixture(); client.listReleases = async () => ({ items: [{ immutableId: "z", tagName: "z", name: "z", draft: false, prerelease: false, createdAt: "2026-08-01T00:00:00Z", publishedAt: null }], pagesRead: 1, continuationAvailable: false }); const snapshot = await createGitHubSourceAdapter({ client }).readSnapshot({ ...input, requestedLimits: createRequestedLimits({ commits: 0, issues: 0, pullRequests: 0, releases: 1, tags: 0 }) }); assert.equal(snapshot.records[2].observedAt, "2026-08-01T00:00:00Z"); }],
    ["branch head is stable source identity", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(snapshot.records[1].sourceRecordId.includes(":main")); }],
    ["client receives normalized ref", async () => { const client = fixture(); await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(client.calls[0][1].repositoryRef, "cyrilla-mist/nexus-ai"); }],
    ["client receives explicit limits", async () => { const client = fixture(); await createGitHubSourceAdapter({ client }).readSnapshot(input); assert.equal(client.calls.find(call => call[0] === "commits")[1].limit, 2); }],
    ["client does not receive credentials", async () => { const client = fixture(); await createGitHubSourceAdapter({ client }).readSnapshot(input); assert(client.calls.every(call => !Object.hasOwn(call[1], "token"))); }],
    ["output has no URL query", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(snapshot.records.every(record => !record.reference.includes("?"))); }],
    ["output has no URL fragment", async () => { const snapshot = await createGitHubSourceAdapter({ client: fixture() }).readSnapshot(input); assert(snapshot.records.every(record => !record.reference.includes("#"))); }],
    ["unknown error is not raw", async () => { const client = fixture(); client.listIssues = async () => { throw new Error("raw-private-response"); }; await assert.rejects(() => createGitHubSourceAdapter({ client }).readSnapshot(input), error => error.code === "SOURCE_UNAVAILABLE" && !JSON.stringify(error).includes("raw-private-response")); }]
  ];
  assert(cases.length >= 50);
  for (const [name, run] of cases) await t.test(name, run);
});
