import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { buildContextPackageV02 } from "../experience/context-v02/context-package-projector.mjs";
import { adaptGeneralizedContextPackageToV02 } from "../experience/context-v03/generalized-context-package-builder.mjs";
import { createSelfContextProvider } from "../experience/context-v02/self-context-provider.mjs";

const fixtureUrl = new URL("../examples/nexus-atlas-self-context-v0.2.json", import.meta.url);
const fixedGeneratedAt = "2026-08-05T12:00:00+08:00";
const explicitGeneratedAt = "2026-08-05T09:00:00+08:00";
const fixture = JSON.parse(await readFile(fixtureUrl, "utf8"));
const provider = createSelfContextProvider({ readFileImpl: () => readFile(fixtureUrl, "utf8") });
const result = await provider.loadContextPackage();
const graph = result.graph;
const legacy = result.contextPackage;
const generalized = result.generalizedContextPackage;
const ledger = result.decisionMemoryLedger;
const project = graph.nodes.find((node) => node.id === "project:nexus-atlas");
const roadmap = graph.nodes.find((node) => node.id === "evidence:v02-roadmap");
const oldAction = graph.nodes.find((node) => node.id === "action:define-phase3-context-package-contract");
const newAction = graph.nodes.find((node) => node.id === "action:review-phase4-source-adapter-entry");
const sum = (values) => Object.values(values).reduce((total, value) => total + value, 0);
const deepFrozen = (value) => !value || typeof value !== "object" || (Object.isFrozen(value) && Object.values(value).every(deepFrozen));

test("canonical graph has 30 nodes and 9 edges", () => { assert.equal(graph.nodes.length, 30); assert.equal(graph.edges.length, 9); });
test("project records the Phase 3 completion boundary", () => { assert.equal(project.payload.currentPhase, "Phase 3 complete; Phase 4 planned"); });
test("project version includes v0.3", () => { assert.equal(project.payload.currentVersion, "v0.2 Personal Context Foundation with Context Package v0.3"); });
test("roadmap evidence is confirmed and current", () => { assert.equal(roadmap.epistemic.verification, "confirmed"); assert.equal(roadmap.epistemic.freshness, "current"); });
test("roadmap evidence claims Phase 3 complete", () => { assert.equal(roadmap.payload.claim, "The Nexus Atlas v0.2 roadmap records Phase 3 as complete and Phase 4 as planned."); });
test("current project evidence and action do not claim Phase 3 planned", () => { assert.equal(JSON.stringify({ project, roadmap, oldAction }).includes("Phase 3 planned"), false); });
test("old Phase 3 action lifecycle is completed", () => { assert.equal(oldAction.lifecycle.state, "completed"); });
test("old Phase 3 action status is completed", () => { assert.equal(oldAction.payload.actionStatus, "completed"); });
test("old action is absent from legacy nextActions", () => { assert.equal(legacy.nextActions.some((item) => item.id === oldAction.id), false); });
test("old action is absent from generalized next actions", () => { assert.equal(generalized.actions.next.some((item) => item.id === oldAction.id), false); });
test("new Phase 4 entry action is active", () => { assert.equal(newAction.lifecycle.state, "active"); });
test("new Phase 4 entry action is current and confirmed", () => { assert.equal(newAction.epistemic.freshness, "current"); assert.equal(newAction.epistemic.verification, "confirmed"); });
test("new Phase 4 entry action is proposed", () => { assert.equal(newAction.payload.actionStatus, "proposed"); });
test("new Phase 4 entry action has no external effect", () => { assert.equal(newAction.payload.externalEffect, false); });
test("new Phase 4 entry action does not require confirmation", () => { assert.equal(newAction.payload.requiresConfirmation, false); });
test("legacy nextActions contains only the new action", () => { assert.deepEqual(legacy.nextActions.map((item) => item.id), [newAction.id]); });
test("generalized next actions contains only the new action", () => { assert.deepEqual(generalized.actions.next.map((item) => item.id), [newAction.id]); });
test("generalized package has 24 records", () => { assert.equal(generalized.sourceSummary.totalIncludedRecords, 24); });
test("legacy package has 19 nodes", () => { assert.equal(legacy.sourceSummary.totalIncludedNodes, 19); });
test("generalized provider totals sum to 24", () => { assert.equal(sum(generalized.sourceSummary.providers), 24); });
test("generalized byKind totals sum to 24", () => { assert.equal(sum(generalized.sourceSummary.byKind), 24); });
test("legacy provider totals sum to 19", () => { assert.equal(sum(legacy.sourceSummary.providers), 19); });
test("Adapter matches Provider v0.2 output", () => { assert.deepEqual(adaptGeneralizedContextPackageToV02(generalized), legacy); });
test("old Projector matches Provider v0.2 output", () => { assert.deepEqual(buildContextPackageV02({ graph, generatedAt: fixedGeneratedAt, decisionMemoryLedger: ledger }), legacy); });
test("default generatedAt is shared by graph, ledger, and packages", () => { assert.equal(graph.metadata.generatedAt, fixedGeneratedAt); assert.equal(ledger.generatedAt, fixedGeneratedAt); assert.equal(legacy.generatedAt, fixedGeneratedAt); assert.equal(generalized.generatedAt, fixedGeneratedAt); });
test("explicit generatedAt remains deterministic", async () => { const explicit = await createSelfContextProvider({ readFileImpl: () => readFile(fixtureUrl, "utf8"), generatedAt: explicitGeneratedAt }).loadContextPackage(); assert.equal(explicit.contextPackage.generatedAt, explicitGeneratedAt); assert.equal(explicit.generalizedContextPackage.generatedAt, explicitGeneratedAt); assert.equal(explicit.decisionMemoryLedger.generatedAt, explicitGeneratedAt); });
test("Provider wrapper is strictly cached", async () => { const first = await provider.loadContextPackage(); const second = await provider.loadContextPackage(); assert.strictEqual(first, second); assert.strictEqual(first.generalizedContextPackage, generalized); });
test("v0.2 and v0.3 outputs are recursively frozen", () => { assert.equal(deepFrozen(legacy), true); assert.equal(deepFrozen(generalized), true); assert.equal(deepFrozen(result), true); });
test("canonical and projected project records are reference-isolated", () => { assert.notStrictEqual(project, legacy.project); assert.notStrictEqual(project, generalized.project); assert.notStrictEqual(legacy.project, generalized.project); });
test("Phase 3A through 3D documentation is complete", async () => { const roadmapText = await readFile(new URL("../docs/Nexus-Atlas-v0.2-Roadmap.md", import.meta.url), "utf8"); const contractText = await readFile(new URL("../docs/Nexus-Atlas-v0.3-Generalized-Context-Package-Contract.md", import.meta.url), "utf8"); assert.match(roadmapText, /Phase 3A.*Complete/); assert.match(roadmapText, /Phase 3B.*Complete/); assert.match(roadmapText, /Phase 3C.*Complete/); assert.match(roadmapText, /Phase 3D.*Complete/); assert.match(contractText, /Phase 3 Generalized Context Package Complete/); });
test("Phase 4 remains planned", async () => { const roadmapText = await readFile(new URL("../docs/Nexus-Atlas-v0.2-Roadmap.md", import.meta.url), "utf8"); assert.match(roadmapText, /Phase 4.*Planned/); });
test("Phase 4 has no runtime, live source, or mutation integration", async () => { const providerText = await readFile(new URL("../experience/context-v02/self-context-provider.mjs", import.meta.url), "utf8"); const builderText = await readFile(new URL("../experience/context-v03/generalized-context-package-builder.mjs", import.meta.url), "utf8"); for (const source of [providerText, builderText]) for (const token of ["fetch(", "process.env", "writeFile", "appendFile", "POST", "add_owners"]) assert.equal(source.includes(token), false); });
test("package-lock remains outside the package scripts", async () => { const packageText = await readFile(new URL("../package.json", import.meta.url), "utf8"); assert.equal(packageText.includes("package-lock.json"), false); });

assert.equal(fixture.nodes.length, 30);
