import assert from "node:assert/strict";
import { readFile, readFileSync } from "node:fs";
import { readFile as readFileAsync } from "node:fs/promises";
import test from "node:test";

import { buildContextPackageV02 } from "../experience/context-v02/context-package-projector.mjs";
import { createSelfContextProvider } from "../experience/context-v02/self-context-provider.mjs";
import { adaptGeneralizedContextPackageToV02 } from "../experience/context-v03/generalized-context-package-builder.mjs";

const fixtureUrl = new URL("../examples/nexus-atlas-self-context-v0.2.json", import.meta.url);
const explicitGeneratedAt = "2026-08-05T09:00:00+08:00";
async function fixtureText() { return readFileAsync(fixtureUrl, "utf8"); }
function deepFrozen(value) { if (!value || typeof value !== "object") return true; return Object.isFrozen(value) && Object.values(value).every(deepFrozen); }
async function explicitResult(options = {}) { return createSelfContextProvider({ readFileImpl: fixtureText, generatedAt: explicitGeneratedAt, ...options }).loadContextPackage(); }

test("Provider preserves old methods and adds the generalized method", () => { const provider = createSelfContextProvider({ readFileImpl: fixtureText }); for (const method of ["loadGraph", "loadDecisionMemoryLedger", "loadContextPackage", "loadGeneralizedContextPackage"]) assert.equal(typeof provider[method], "function"); });
test("Provider mode and source remain compatible", () => { const provider = createSelfContextProvider({ readFileImpl: fixtureText }); assert.equal(provider.mode, "self-context-v02"); assert.equal(provider.source, "deterministic-fixture"); });
test("fixture is read once and Graph is cached", async () => { let reads = 0; const provider = createSelfContextProvider({ readFileImpl: async () => { reads += 1; return fixtureText(); } }); const first = await provider.loadGraph(); const second = await provider.loadGraph(); await provider.loadContextPackage(); await provider.loadGeneralizedContextPackage(); assert.equal(reads, 1); assert.strictEqual(first, second); });
test("Ledger, v0.3 Package, and wrapper are cached", async () => { const provider = createSelfContextProvider({ readFileImpl: fixtureText }); const ledger = await provider.loadDecisionMemoryLedger(); const ledgerAgain = await provider.loadDecisionMemoryLedger(); const generalized = await provider.loadGeneralizedContextPackage(); const generalizedAgain = await provider.loadGeneralizedContextPackage(); const result = await provider.loadContextPackage(); const resultAgain = await provider.loadContextPackage(); assert.strictEqual(ledger, ledgerAgain); assert.strictEqual(generalized, generalizedAgain); assert.strictEqual(result, resultAgain); assert.strictEqual(result.generalizedContextPackage, generalized); });
test("v0.2 and v0.3 packages use one generatedAt", async () => { const result = await explicitResult(); assert.equal(result.decisionMemoryLedger.generatedAt, explicitGeneratedAt); assert.equal(result.contextPackage.generatedAt, explicitGeneratedAt); assert.equal(result.generalizedContextPackage.generatedAt, explicitGeneratedAt); });
test("v0.3 package has accepted section counts", async () => { const p = (await explicitResult()).generalizedContextPackage; assert.equal(p.packageVersion, "0.3"); assert.equal(p.decisions.effective.length, 6); assert.equal(p.decisions.proposed.length, 0); assert.equal(p.decisions.chains.length, 6); assert.equal(p.memories.inherited.length, 3); assert.equal(p.memories.inferred.length, 1); assert.equal(p.memories.disputed.length, 0); assert.equal(p.memories.historical.length, 1); assert.equal(p.evidence.current.length, 5); assert.equal(p.risks.open.length, 5); assert.equal(p.actions.next.length, 1); assert.equal(p.conflicts.unresolved.length, 0); assert.equal(p.sourceSummary.totalIncludedRecords, 24); });
test("v0.2 compatibility package has accepted counts", async () => { const p = (await explicitResult()).contextPackage; assert.equal(p.packageVersion, "0.2"); assert.equal(p.sourceSummary.totalIncludedNodes, 19); assert.equal(p.confirmedDecisions.length, 6); assert.equal(p.currentEvidence.length, 5); assert.equal(p.staleContext.length, 1); assert.equal(p.openRisks.length, 5); assert.equal(p.nextActions.length, 1); });
test("Adapter and old Projector both match v0.2 output", async () => { const result = await explicitResult(); const expected = buildContextPackageV02({ graph: result.graph, generatedAt: explicitGeneratedAt, decisionMemoryLedger: result.decisionMemoryLedger }); assert.deepEqual(result.contextPackage, expected); assert.deepEqual(adaptGeneralizedContextPackageToV02(result.generalizedContextPackage), expected); });
test("sourceInfo preserves old fields and exposes integration fields", async () => { const info = (await explicitResult()).sourceInfo; for (const field of ["mode", "label", "live", "readOnly", "deterministic", "runtimeEvidence", "decisionMemoryIntegrated", "ledgerVersion", "nodeCount", "edgeCount", "decisionCount", "memoryCount", "effectiveDecisionCount", "chainCount", "conflictCount"]) assert.ok(field in info); assert.equal(info.mode, "self-context-v02"); assert.equal(info.generalizedContextPackageIntegrated, true); assert.equal(info.legacyAdapterIntegrated, true); assert.equal(info.contextPackageVersion, "0.2"); assert.equal(info.generalizedContextPackageVersion, "0.3"); assert.equal(info.legacyIncludedNodeCount, 19); assert.equal(info.generalizedIncludedRecordCount, 24); });
test("wrapper and all Provider outputs are recursively frozen", async () => { const result = await explicitResult(); assert.equal(deepFrozen(result.graph), true); assert.equal(deepFrozen(result.decisionMemoryLedger), true); assert.equal(deepFrozen(result.contextPackage), true); assert.equal(deepFrozen(result.generalizedContextPackage), true); assert.equal(deepFrozen(result.sourceInfo), true); assert.equal(deepFrozen(result), true); });
test("Graph nodes and package records are reference isolated", async () => { const result = await explicitResult(); assert.notStrictEqual(result.graph.nodes.find((node) => node.id === "project:nexus-atlas"), result.contextPackage.project); assert.notStrictEqual(result.graph.nodes.find((node) => node.id === "project:nexus-atlas"), result.generalizedContextPackage.project); assert.notStrictEqual(result.generalizedContextPackage.project, result.contextPackage.project); });
test("default generatedAt comes from Graph metadata", async () => { const result = await createSelfContextProvider({ readFileImpl: fixtureText }).loadContextPackage(); assert.equal(result.graph.metadata.generatedAt, "2026-08-03T23:30:00+08:00"); assert.equal(result.decisionMemoryLedger.generatedAt, result.graph.metadata.generatedAt); assert.equal(result.generalizedContextPackage.generatedAt, result.graph.metadata.generatedAt); assert.equal(result.contextPackage.generatedAt, result.graph.metadata.generatedAt); assert.equal(result.generalizedContextPackage.packageId, "context-package:project-nexus-atlas:2026-08-03T23-30-00-08-00"); });
test("v0.2 package excludes v0.3-only top-level fields", async () => { const p = (await explicitResult()).contextPackage; for (const field of ["decisions", "memories", "conflicts", "scope", "generalizedContextPackage"]) assert.equal(field in p, false); });
test("v0.3 package excludes internal raw inputs", async () => { const p = (await explicitResult()).generalizedContextPackage; assert.equal("rawGraph" in p, false); assert.equal("rawLedger" in p, false); });
test("consent is copied and affects only Ledger governance", async () => { const consentedRecordIds = ["memory:github-adapter-proposed"]; const provider = createSelfContextProvider({ readFileImpl: fixtureText, consentedRecordIds }); consentedRecordIds.push("memory:unexpected"); const result = await provider.loadContextPackage(); assert.equal(result.decisionMemoryLedger.inferredMemories.some((item) => item.id === "memory:github-adapter-proposed"), true); assert.equal(result.generalizedContextPackage.memories.inferred.some((item) => item.id === "memory:github-adapter-proposed"), true); assert.equal(result.contextPackage.staleContext.some((item) => item.id === "memory:github-adapter-proposed"), false); assert.equal(result.decisionMemoryLedger.omittedRecords.some((item) => item.id === "memory:unexpected"), false); assert.deepEqual(adaptGeneralizedContextPackageToV02(result.generalizedContextPackage), result.contextPackage); });
test("invalid consent is rejected at Provider creation", () => { for (const value of ["memory:id", new Set(["memory:id"]), {}, 1, ["memory:id", 1]]) assert.throws(() => createSelfContextProvider({ consentedRecordIds: value }), { name: "TypeError" }); });
test("malformed JSON remains a SyntaxError", async () => { const provider = createSelfContextProvider({ readFileImpl: async () => "{not json" }); await assert.rejects(() => provider.loadGraph(), SyntaxError); await assert.rejects(() => provider.loadContextPackage(), SyntaxError); });
test("invalid Graph errors remain visible", async () => { const provider = createSelfContextProvider({ readFileImpl: async () => JSON.stringify({ metadata: {} }) }); await assert.rejects(() => provider.loadGraph(), /metadata|nodes/i); await assert.rejects(() => provider.loadContextPackage(), /metadata|nodes/i); });
test("failed Graph Promise remains cached as a rejection", async () => { let reads = 0; const provider = createSelfContextProvider({ readFileImpl: async () => { reads += 1; return JSON.stringify({ metadata: {} }); } }); await assert.rejects(() => provider.loadContextPackage()); await assert.rejects(() => provider.loadContextPackage()); assert.equal(reads, 1); });
test("Provider does not call global fetch", async () => { const original = globalThis.fetch; let called = false; globalThis.fetch = () => { called = true; throw new Error("unexpected"); }; try { await explicitResult(); assert.equal(called, false); } finally { globalThis.fetch = original; } });
test("Provider does not call Date.now or Math.random", async () => { const originalNow = Date.now; const originalRandom = Math.random; Date.now = () => { throw new Error("unexpected"); }; Math.random = () => { throw new Error("unexpected"); }; try { await explicitResult(); } finally { Date.now = originalNow; Math.random = originalRandom; } });
test("Provider source has no environment or mutation integration", () => { const source = readFileSync(new URL("../experience/context-v02/self-context-provider.mjs", import.meta.url), "utf8"); for (const token of ["process.env", "POST", "add_owners"]) assert.equal(source.includes(token), false); });
test("Provider uses no mutable package fields", async () => { const result = await explicitResult(); assert.equal(Object.isFrozen(result.contextPackage), true); assert.equal(Object.isFrozen(result.generalizedContextPackage), true); assert.equal(Object.isFrozen(result.sourceInfo), true); });
test("Provider source does not call the old Projector", () => { const source = readFileSync(new URL("../experience/context-v02/self-context-provider.mjs", import.meta.url), "utf8"); assert.equal(source.includes("buildContextPackageV02"), false); assert.equal(source.includes("buildGeneralizedContextPackage"), true); assert.equal(source.includes("adaptGeneralizedContextPackageToV02"), true); });
test("Provider v0.3 test fixture remains the canonical fixture", async () => { const graph = JSON.parse(await readFileAsync(fixtureUrl, "utf8")); const result = await explicitResult(); assert.equal(result.graph.nodes.length, graph.nodes.length); assert.equal(result.graph.edges.length, graph.edges.length); });
